# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
    so-timeout: 1501
    connect-timeout: 601
#缩略图生成参数
    thumb-image:
        width: 150
        height: 150
#TrackerList参数,支持多个
    tracker-list:
        - 192.168.42.130:22122
